server:
  port: 8082

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/account}
    username: ${DATASOURCE_USER:root}
    password: ${DATASOURCE_PASSWORD:secret}
  kafka:
    producer:
      bootstrap-servers: localhost:9092

logging:
  level:
    org.springframework.web: INFO
    com.demobank: DEBUG
    org.springframework.jdbc: DEBUG