server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: account.command-api
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      database: ${MONGO_DB:account}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      auto-index-creation: true
      authentication-database: ${MONGO_AUTH_DB:account}

