server:
  port: 8081

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USER:account}
      password: ${MONGO_PASSWORD:secret}

logging:
  level:
    org.springframework.web: INFO
    com.demobank: DEBUG
    org.springframework.jdbc: DEBUG